# Generated by Django 6.0 on 2025-12-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц (USD)')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('telegram_url', models.URLField(help_text='Например: https://t.me/username', verbose_name='Ссылка на Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='CSS-цвет, например: #2dd4bf или rgb(45,212,191)', max_length=20)),
                ('icon', models.CharField(help_text='Например: emoji (🏖️) или CSS-класс иконки.', max_length=50)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Для сортировки фотографий', verbose_name='Порядок')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.tag'),
        ),
    ]
